# CHAPTER 6 - PANDAS IN DEPTH - DATA MANIPULATION

## Part 1

## Data Preparation

## Merging

The merging operation ccombines data through the connection of rows using one or more keys.

On the basis of these keys, it is possible to obtain new data in a tabular form as the result of the combination of other tables. 

This operation with the library pandas is called merging, and merge() is the function to perform this kind of operation.

In [2]:
import numpy as np
import pandas as pd

In [3]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'price': [12.33,11.44,33.21,13.23,33.62]})
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [4]:
frame2 = pd.DataFrame( {'id': ['pencil','pencil','ball','pen'],
                        'color':['white','red','red','black']})
frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

Carry out the merging by applying the merge() function to the two dataframe objects.

In [5]:
pd.merge(frame1,frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

The returned dataframe consists of all rows that have an ID in common.

In addition to the common column, the columns from the first and
the second dataframe are added.

It is necessary to explicitly define the criteria for merging that pandas must follow, specifying the name of the key column using the "on" option.

In [9]:
# add the on option with the column name as the key for the merging
frame1 = pd.DataFrame( {'id': ['ball','pencil','pen',',mug','ashtray'],
                        'color': ['white','red','red','black','green'],
                        'brand': ['OMG','ABC','ABC','POD','PPOD']})
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3     ,mug  black   POD
4  ashtray  green  PPOD

In [10]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'brand': ['OMG','POD','ABC','POD']})
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [11]:
#In this case you have two dataframes having columns with the same name. 
#So if you launch a merge, you do not get any results.
pd.merge(frame1,frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

In [12]:
pd.merge(frame1, frame2, on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [13]:
pd.merge(frame1, frame2, on='brand')

id_x  color brand    id_y
0    ball  white   OMG  pencil
1  pencil    red   ABC    ball
2     pen    red   ABC    ball
3    ,mug  black   POD  pencil
4    ,mug  black   POD     pen

Very often, the opposite problem arises, that is, to have two dataframes in which the key columns do not have the same name.

If you have two dataframes in which the key columns do not have the same name. 

You have to use the left_on and right_on options, which specify the key column for the first and for the second dataframe.

In [14]:
frame2.columns = ['sid','brand']
frame2

sid brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [15]:
pd.merge(frame1, frame2, left_on="id", right_on="sid")

id  color brand_x     sid brand_y
0    ball  white     OMG    ball     ABC
1  pencil    red     ABC  pencil     OMG
2  pencil    red     ABC  pencil     POD
3     pen    red     ABC     pen     POD

By default, the merge() function performs an inner join; the keys in the result are the result of an intersection.

Other possible options are the left join, the right join, and the outer join. 

The outer join produces the union of all keys, combining the effect of a left join with a right join. 

To select the type of join you have to use the how option.

In [16]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3     ,mug  black   POD
4  ashtray  green  PPOD

In [17]:
frame2

sid brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [18]:
frame2.columns = ['id','brand']
pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [19]:
pd.merge(frame1,frame2,on='id',how='outer')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4     ,mug  black     POD     NaN
5  ashtray  green    PPOD     NaN

### Merging on Index

In some cases, instead of considering the columns of a dataframe as keys, indexes could be used as keys for merging. 

In order to decide which indexes to consider, you set the left_index or right_index options to True to activate them, with the ability to activate them both.

In [20]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3     ,mug  black   POD
4  ashtray  green  PPOD

In [21]:
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [22]:
pd.merge(frame1,frame2,right_index=True, left_index=True)

id_x  color brand_x    id_y brand_y
0    ball  white     OMG  pencil     OMG
1  pencil    red     ABC  pencil     POD
2     pen    red     ABC    ball     ABC
3    ,mug  black     POD     pen     POD

The dataframe objects have a join() function, which is much more convenient when you want to do the merging by indexes. 

It can also be used to combine many dataframe objects having the same or the same indexes but with no columns overlapping.

In [23]:
#You will get an error code because some columns in frame1 have the same  name aframe2. 
#A solution will be to rename the columns in frame2 before launching the join() function.
frame1.join(frame2)

ValueError: columns overlap but no suffix specified: Index(['id', 'brand'], dtype='object')

In [24]:
frame2.columns = ['brand2','id2']
frame1.join(frame2)

id  color brand  brand2  id2
0     ball  white   OMG  pencil  OMG
1   pencil    red   ABC  pencil  POD
2      pen    red   ABC    ball  ABC
3     ,mug  black   POD     pen  POD
4  ashtray  green  PPOD     NaN  NaN

## Concatenating

Another type of data combination is referred to as concatenation (i.e. a series of interconnected things) 

NumPy provides a concatenate() function to do this kind of operation with arrays

In [25]:
array1 = np.arange(9).reshape((3,3))
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
array2 = np.arange(9).reshape((3,3))+6
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [27]:
np.concatenate([array1,array2],axis=1) #axis=1 for columns

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [28]:
np.concatenate([array1,array2],axis=0) #axis=0 for rows

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

With the pandas library and its data structures like series and dataframe, having labeled axes allows you to further generalize the concatenation of arrays. 

The concat() function is provided by pandas for this kind of operation.

In [ ]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])
ser1

In [ ]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])
ser2

In [ ]:
#Use concat() function if you have labeled axes
#By default, the concat() function works on axis = 0 (for rows)
pd.concat([ser1,ser2])

In [ ]:
#If you set the axis = 1, then the result will be a dataframe.
pd.concat([ser1,ser2], axis=1)

In [ ]:
#To create a hierarchical index on the axis of concatenation, use the keys option
pd.concat([ser1,ser2], keys=[1,2])

In the case of combinations between series along the axis = 1 the keys become the column headers of the dataframe.

In [ ]:
pd.concat([ser1,ser2], axis=1, keys=[1,2])

In [ ]:
#concatenation can be applied to the dataframes
frame1 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[1,2,3], columns=['A','B','C'])
frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[4,5,6], columns=['A','B','C'])
pd.concat([frame1, frame2])

In [ ]:
pd.concat([frame1, frame2], axis=1) #If you set the axis = 1, then the result will be a dataframe.

### Combining

There is another situation in which there is combination of data that cannot be obtained either with merging or with concatenation. 

Take the case in which you want the two datasets to have indexes that overlap in their entirety or at least partially.

One applicable function to series is combine_first(), which performs this kind of
operation along with data alignment.

In [ ]:
ser1 = pd.Series(np.random.rand(5), index=[1,2,3,4,5])
ser1

In [ ]:
ser2 = pd.Series(np.random.rand(4), index=[2,4,5,6])
ser2

In [ ]:
ser1.combine_first(ser2)

In [ ]:
ser2.combine_first(ser1)

If you want a partial overlap, you can specify only the portion of the series you want to overlap.

In [ ]:
ser1[:3].combine_first(ser2[:3])

## Pivoting (Reshaping)

In addition to assembling the data in order to unify the values collected from different
sources, another fairly common operation is pivoting.

### Pivoting with Hierarchical Indexing

To rearrange the data by column values on rows or vice versa 

Stacking—Rotates or pivots the data structure converting columns to rows

Unstacking—Converts rows into columns

In [ ]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
                     index=['white','black','red'],
                     columns=['ball','pen','pencil'])
frame1

In [ ]:
ser = frame1.stack()
ser

In [ ]:
ser.unstack()

In [ ]:
# We can also do the unstack on a different level, specifying the number of levels or its
#name as the argument of the function.
ser.unstack(0) # Similar to transposing

### Removing

In [ ]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
                       index=['white','black','red'],
                       columns=['ball','pen','pencil'])
frame1

In [ ]:
del frame1['ball'] # delete column
frame1

In [ ]:
frame1.drop('white') # delete row

## Data Transformation

### Removing Duplicates

Duplicate rows might be present in a dataframe for various reasons. In dataframes of enormous size, the detection of these rows can be very problematic. 

In this case, pandas provides a series of tools to analyze the duplicate data present in large data structures.

In [ ]:
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'],
                        'value': [2,1,3,3,2]})
dframe

The duplicated() function applied to a dataframe can detect the rows that appear to be duplicated. 

It returns a series of Booleans where each element corresponds to a row,
with True if the row is duplicated (i.e., only the other occurrences, not the first), and with False if there are no duplicates in the previous elements.

In [ ]:
dframe.duplicated()

In [ ]:
#To know the duplicate rows
dframe[dframe.duplicated()]

In [ ]:
#To delete duplicated rows
df=dframe.drop_duplicates()
df

### Replacing Values via Mapping

The pandas library provides a set of functions which exploit mapping to perform some operations. 

Mapping is the creation of a list of matches between two different values,  with the ability to bind a value to a particular label or string

In [ ]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
                       'color':['white','rosso','verde','black','yellow'],
                       'price':[5.56,4.20,1.30,0.56,2.75]})
frame

In [ ]:
#To define mapping, use a dict object.
#Replacing Values via Mapping
newcolors = {
    'rosso': 'red',
    'verde': 'green',
    'ashtray':'book'
}
newcolors

In [ ]:
frame.replace(newcolors)

In [ ]:
ser = pd.Series([1,3,np.nan,4,6,np.nan,3])
ser

In [ ]:
ser.replace(np.nan,0)

### Adding Values via Mapping

In [ ]:
#Adding Values via Mapping
#The map() function applied to a series or to a column of a dataframe accepts a function or an object containing a dict
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
                 'color':['white','red','green','black','yellow']})
frame

In [ ]:
#Def a dict object
price = {
    'ball': 5.56,
    'mug': 4.20,
    'bottle': 1.30,
    'scissors': 3.41,
    'pen': 1.30,
    'pencil': 0.56,
    'ashtray': 2.75
}
price

In [ ]:
frame['price'] = frame['item'].map(price)
frame

### Rename the Indexes of the Axes

In [ ]:
frame

In [ ]:
reindex = {
    0: 'first',
    1: 'second',
    2: 'third',
    3: 'fourth',
    4: 'fifth'
}
frame.rename(reindex) # indexes are renamed

In [ ]:
recolumn = {
    'item': 'object',
    'price': 'value'
}
frame.rename(index=reindex, columns=recolumn) # columns are renamed

## Discretization and Binning

A more complex process of data transformation is discretization.

It is used in experimental cases, to handle large quantities of data generated in sequence.

It involves transforming the data into discrete categories, for example, by dividing the range of values of such readings into smaller intervals and counting the occurrence or statistics in them.

In [ ]:
results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]
bins = [0,25,50,75,100]
cat = pd.cut(results, bins)
#The object returned by the cut() function is a special object of Categorical type
type(cat)

In [ ]:
cat.categories # indicate the names of the different internal categories

In [ ]:
cat.codes # list of numbers equal to the elements of results

In [ ]:
#how many results fall into each category? use the value_counts() function
pd.value_counts(cat)

In [ ]:
#You can give names to various bins by calling them first in an array of strings
#and then assigning to the labels options inside the cut() function 
bin_names = ['unlikely','less likely','likely','highly likely']
cat2 = pd.cut(results, bins, labels=bin_names)
pd.value_counts(cat2)

In [ ]:
#If the cut() function is passed as an argument to an integer instead of explicating the bin edges, 
#this will divide the range of values of the array in many intervals as specified by the number.
cat3=pd.cut(results, 5) #Group into 5 categories
cat3

In [ ]:
pd.value_counts(cat3)

In [ ]:
#pandas provides another method for binning: qcut() 
#qcut() will ensure that the number of occurrences for each bin is equal, but the edges of each bin vary.
quintiles = pd.qcut(results, 5)
quintiles

In [ ]:
pd.value_counts(quintiles)

### Detecting and Filtering Outliers

In [ ]:
# create a dataframe with three columns from 1,000 completely random values:
randframe = pd.DataFrame(np.random.randn(1000,3))
randframe

In [ ]:
#Use describe() function you can see the statistics for each column.
randframe.describe()

In [ ]:
#Use the std() function to have the standard deviation of each column of the dataframe
randframe.std()

In [ ]:
#Apply the filtering of all the values of the dataframe, 
#applying the corresponding standard deviation for each column. 
#Use any() function , you can apply the filter on each column.
randframe[(np.abs(randframe) > (3*randframe.std())).any(1)]

## Permutation

The operations of permutation (random reordering) of a series or the rows of a dataframe are easy to do using the numpy.random.permutation() function.

In [ ]:
#create a dataframe containing integers in ascending order.
nframe = pd.DataFrame(np.arange(25).reshape(5,5))
nframe

In [ ]:
#create an array of five integers from 0 to 4 arranged in random order with the permutation() function.
new_order = np.random.permutation(5)
new_order

In [ ]:
#Now apply it to the dataframe on all lines, using the take() function.
nframe.take(new_order)

We can submit even a portion of the entire dataframe to a permutation. 

It generates an array that has a sequence limited to a certain range, for example, in our case from 2 to 4.

In [ ]:
new_order = [3,4,2]
nframe.take(new_order)

### Random Sampling

Sometimes, when you have a huge dataframe, you may need to sample
it randomly, and the quickest way to do this is by using the np.random.randint() function.

In [ ]:
sample = np.random.randint(0, len(nframe), size=3)
sample

In [ ]:
nframe.take(sample)